services:
  mongo:
    image: mongo:8
    restart: always
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER?Variable not set}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD?Variable not set}
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - default
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - MONGO_SERVER=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER?Variable not set}
      - MONGO_PASSWORD=${MONGO_PASSWORD?Variable not set}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/utils/health-check/']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
